// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xlkubyfskxqgqibfuiqd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhsa3VieWZza3hxZ3FpYmZ1aXFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzNDExNTMsImV4cCI6MjA3MDkxNzE1M30.4iSMxrU2svOipRmPFdTR9nfeDdIBpw2m4bhjaSqgRoY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});