// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gdxqmqwdvxozhhlvhfvp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdkeHFtcXdkdnhvemhobHZoZnZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzNDA4NjIsImV4cCI6MjA3MDkxNjg2Mn0.g-jGwunsx7kyXOncj0VDDEiwRN4sm9SKj_g3QGk2ZLY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});